### ISSUE TITLE
Discrim ist INT - PROBLEM

### ISSUE THREAD

**Issue by Crypti-x** [Entwicklertreff/Levelbot#6]
Wenn Der Discrim mit 0 beginnt oder 0 vor anderen Zahlen im Discrim sind, werden nur die anderen Ziffern angezeigt, weil INT. Siehe https://entwickler.cc/levels.
Bitte fixen. Kompabilität mit aktueller Version muss erhalten bleiben, DB muss variabel angepasst werden. (INT -> STR).

**Comment by romangraef** [comment]
das sollte im rendering geändert werden. ist der auch open source?

**Comment by Crypti-x** [comment]
solved
