### ISSUE TITLE
.gitignore needs a new entry

### ISSUE THREAD

**Issue by DeepRobin** [Entwicklertreff/Levelbot#7]
**Description:**
Why is files/settings.json "uploaded"?
It should be generated by the application.

Kind regards, 
Robin

**Comment by Crypti-x** [comment]
just ignore it.

**Comment by DeepRobin** [comment]
Why ignore it?
It should follow the official Git Style Guide*. According to the Git Style Guide*, standard configuration files should not be included in the Git Repository. After all, the. gitignore is not there for nothing.

*= I don't know if the Git Style Guide is called but somewhere on the Git documentation it is available and I've read it often enough.

Kind regards,
Robin
